### ISSUE TITLE
Cannot install CMake on Linux

### ISSUE THREAD

**Issue by annulen** [lasote/conan-cmake-installer#1]
I'm getting same error when trying to install any CMake version
```
ERROR: cmake_installer: hostname 'cmake.org' doesn't match either of '*.kitware.com', 'kitware.com'
```

**Comment by lasote** [comment]
It's working for me. It looks like a certificate verification problem, don't know why... Could you run `openssl version` and paste the output? Thanks

**Comment by annulen** [comment]
OpenSSL 1.0.1f 6 Jan 2014

**Comment by lasote** [comment]
Are you using the "deb" conan installer or the pypi package (pip install..)?

**Comment by annulen** [comment]
pypi

**Comment by lasote** [comment]
I've updated the recipe to not check the cmake.org certificate. Please, try now!

**Comment by annulen** [comment]
It works now, thanks!
Have you figured out why doe it fail? Because of redirect?

**Comment by lasote** [comment]
The problem was the old openssl version. It doesn't handle right the domain certificates with multidomain. CMake site has a singlecertificate for kitware.com and others. I deactivated the certificate check. 
You are welcome!
