### ISSUE TITLE
Versioning management

### ISSUE THREAD

**Issue by GamePad64** [lasote/conan-cmake-installer#5]
Hello,
Why this package uses the custom versioning scheme, not the Conan's native one? Seems very distractive to me.

**Comment by lasote** [comment]
Sorry, what?

**Comment by GamePad64** [comment]
Why are you using `options = {"version": available_versions}` instead of just uploading multiple conanfiles to bintray?

**Comment by lasote** [comment]
Specifying an option is a problem or a pain for you or it's just a preference?

**Comment by GamePad64** [comment]
Just a preference, primarily for consistency reasons.

**Comment by memsharded** [comment]
This was already addressed, there are ``cmake_installer/3.X.Y`` packages in https://bintray.com/conan-community/conan/cmake_installer%3Aconan now. I guess this can be closed
