### ISSUE TITLE
When using this as a build_requirement it is copying Qt dlls and msvcp120.dll into the bin directory

### ISSUE THREAD

**Issue by L-M-V** [lasote/conan-cmake-installer#7]
I currently don't have CMake installed on my Windows machine and having been adding:

```
    def build_requirements(self):
        self.build_requires("cmake_installer/1.0@conan/stable")
```
to build the default test_packages created by `conan new "demo/testing" -t`

I've noticed that it is copying the following files into my test_package build/hash/bin directory:
```
msvcp120.dll
msvcr120.dll
Qt5Core.dll
Qt5Gui.dll
Qt5Widgets.dll
```
which have been copied from the CMake bin directory. These files should only be required for the execution of cmake.exe (and most likely cmake-gui.exe for the qt files) and not the dependent application.

**Comment by lasote** [comment]
Hi, sorry for the delay. But you are using in your package an import() method and copying the dlls, right? I'm not saying it's ok, just trying to understand the issue.

**Comment by L-M-V** [comment]
Yeah, it's not a huge problem as it deletes these dlls before the package step, but if the item you're building already has these files they will conflict.

Here's a minimum test case (tested on 0.28.0):

Run `conan create test/test`
```
from conans import ConanFile, CMake
import os

class CopyCmakeDlls(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    name = "CopyCmakeDlls"
    version = "1.0"
    
    def build_requirements(self):
        self.build_requires("cmake_installer/1.0@conan/stable")

    def build(self):
        os._exit(1)

    def imports(self):
        self.copy("*.dll", dst="bin", src="bin")
```

Note, os._exit(1) will get the repo into a bad state, and you won't be able to run `conan create test/test` again (it freezes just after the linter because of locks I assume) - but that's to be expected after running such a bad function...

Anyway, this prevents cleanup of the imports and you can see that they exist in the /build/ directory at the time. 

I think a solution would be is to not package the cmake dlls so that they are not brought in by the import statement. Or more generally for the imports step not to apply to build_requirements (perhaps if it is needed, to have a "build_imports" instead.

**Comment by lasote** [comment]
Hi, sorry for the delay, you can use the "root_package" argument to specify the package name where to copy the dlls: http://docs.conan.io/en/latest/reference/conanfile_txt.html?highlight=excludes
You cannot exclude a package, but at least you could repeat the `copy` for the desired requirements.

**Comment by lasote** [comment]
Tell me if it works and it fits for you and feel free to write again. anyway it's a general conan issue, so probably we should open in the conan repository the issue if it's not enough.
